services:
  api-solid-pg:
    image: bitnami/postgresql
    user: root
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=ignitenode03
    volumes:
      - ./pgdata:/bitnami/postgresql